/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package scanner;

import java.awt.Frame;
import java.awt.geom.Rectangle2D;
import javax.swing.JDialog;

import org.jgraph.JGraph;
import org.jgraph.graph.AttributeMap;
import org.jgraph.graph.DefaultGraphCell;
import org.jgraph.graph.GraphConstants;
import org.jgrapht.ListenableGraph;

import org.jgrapht.ext.JGraphModelAdapter;
import org.jgrapht.graph.DefaultEdge;
import org.jgrapht.graph.ListenableUndirectedGraph;
/**
 *
 * @author anwer
 */
public class Graph extends JDialog {

    /**
     * Creates new form Graph
     * @param parent
     * @param modal
     */
    public Graph(Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        createStringGraph();
        
        JGraph graph = new JGraph( m_jgAdapter );
        //graph.setPreferredSize(new Dimension(800, 600));
//        graph.setEnabled(false);
        
        jScrollPane1.getViewport().add(graph);
    }
    
    private void createStringGraph()
    {
        graph = new ListenableUndirectedGraph(DefaultEdge.class);
        
        m_jgAdapter = new JGraphModelAdapter(graph);
        
        Node v1 = new Node(null, "root");
        Node v2 = new Node(v1, "child 1");
        
        v1.addChild(v2);
        v1.addChild(new Node(v1, "child 2"));
        v1.addChild(new Node(v1, "child 3"));
        
        v2.addChild(new Node(v2, "child 11"));
        v2.addChild(new Node(v2, "child 12"));

        // add the vertices
        //g.addVertex(v1);
        
        // add edges to create a circuit
        //g.addEdge(v1, v2);
        
        //positionVertexAt(v1, 1280/2, 0);
        drawTree(v1, CANVAS_WIDTH, 0, reached_height);
        reached_height += 5 * TREE_MARGIN_HEIGHT;
    }
    
    private void drawTree(Node n, Integer width, Integer x, Integer y) {
        if (n == null)
            return;
        
        graph.addVertex(n);
        
        if (n.parent() != null) 
            graph.addEdge(n.parent(), n);
        
        positionVertexAt(n, ((width + x) + x) / 2, y);
        
        if (n.childrenCount() != 0) {
            for (int i = 0; i < n.childrenCount(); i++) {
                drawTree(
                    n.children().get(i),
                    width/n.childrenCount(),
                    i * width/n.childrenCount(),
                    y + LEVEL_MARGIN_HEIGHT
                );
            }
        }
        
    }
    
    private void positionVertexAt( Object vertex, int x, int y ) {
        DefaultGraphCell cell = m_jgAdapter.getVertexCell(vertex);
        AttributeMap attr = cell.getAttributes();
        Rectangle2D bounds = GraphConstants.getBounds(attr);

        Rectangle2D newBounds = 
                new Rectangle2D.Double(
                    x - bounds.getWidth()/2,
                    y,
                    bounds.getWidth(),
                    bounds.getHeight()
                );

        GraphConstants.setBounds(attr, newBounds);

        // TODO: Clean up generics once JGraph goes generic
        AttributeMap cellAttr = new AttributeMap();
        cellAttr.put(cell, attr);
        m_jgAdapter.edit(cellAttr, null, null, null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setSize(new java.awt.Dimension(800, 600));

        jScrollPane1.setHorizontalScrollBarPolicy(javax.swing.ScrollPaneConstants.HORIZONTAL_SCROLLBAR_NEVER);
        jScrollPane1.setHorizontalScrollBar(null);
        jScrollPane1.setMinimumSize(new java.awt.Dimension(1280, 720));
        jScrollPane1.setPreferredSize(new java.awt.Dimension(1280, 720));
        getContentPane().add(jScrollPane1, java.awt.BorderLayout.CENTER);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private ListenableUndirectedGraph graph;
    private JGraphModelAdapter m_jgAdapter;
    private final Integer CANVAS_WIDTH = 1280;
    private final Integer LEVEL_MARGIN_HEIGHT = 80;
    private final Integer TREE_MARGIN_HEIGHT = 100;
    private Integer reached_height = 20; // initially 20px height margin
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables
}
