/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package scanner;

import java.awt.Frame;
import java.awt.geom.Rectangle2D;
import java.util.ArrayList;
import javax.swing.JDialog;

import org.jgraph.JGraph;
import org.jgraph.graph.AttributeMap;
import org.jgraph.graph.DefaultGraphCell;
import org.jgraph.graph.GraphConstants;

import org.jgrapht.ext.JGraphModelAdapter;
import org.jgrapht.graph.DefaultEdge;
import org.jgrapht.graph.ListenableUndirectedGraph;
/**
 *
 * @author anwer
 */
public class Graph extends JDialog {

    /**
     * Creates new form Graph
     * @param trees
     * @param parent
     * @param modal
     */
    public Graph(ArrayList<Node> trees, Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        
        graph = new ListenableUndirectedGraph(DefaultEdge.class);
        m_jgAdapter = new JGraphModelAdapter(graph);
  
        trees.forEach((n) -> {
            drawTree(n, CANVAS_WIDTH, 0, reached_depth);
        });
        
        JGraph graphicalGraph = new JGraph( m_jgAdapter );
        // graph.setPreferredSize(new Dimension(800, 600));
        graphicalGraph.setEnabled(false);
        jScrollPane1.getViewport().add(graphicalGraph);
    }
    
    private void drawTree(Node n, double width, double x, double y) {
        if (n == null)
            return;
        
        graph.addVertex(n);
        
        if (n.parent() != null) 
            graph.addEdge(n.parent(), n);
        
        positionVertexAt(n, ((width + x) + x) / 2, y);
        
        if (n.childrenCount() != 0) {
            for (int i = 0; i < n.childrenCount(); i++) {
                drawTree(
                    n.children().get(i),
                    width/n.childrenCount(),
                    i * width/n.childrenCount(),
                    y + LEVEL_MARGIN_DEPTH
                );
            }
        } else { // might be the deepest node in the tree
            double depth  = getVertexDepth(n);
            if (depth + TREE_MARGIN_DEPTH > reached_depth)
                reached_depth = depth + TREE_MARGIN_DEPTH;
        }
        
    }
    
    private double getVertexDepth(Object vertex) {
        DefaultGraphCell cell = m_jgAdapter.getVertexCell(vertex);
        AttributeMap attr = cell.getAttributes();
        Rectangle2D bounds = GraphConstants.getBounds(attr);
        
        return bounds.getY();
    }
    
    private void positionVertexAt( Object vertex, double x, double y ) {
        DefaultGraphCell cell = m_jgAdapter.getVertexCell(vertex);
        AttributeMap attr = cell.getAttributes();
        Rectangle2D bounds = GraphConstants.getBounds(attr);

        Rectangle2D newBounds = 
                new Rectangle2D.Double(
                    x - bounds.getWidth()/2,
                    y,
                    bounds.getWidth(),
                    bounds.getHeight()
                );

        GraphConstants.setBounds(attr, newBounds);

        // TODO: Clean up generics once JGraph goes generic
        AttributeMap cellAttr = new AttributeMap();
        cellAttr.put(cell, attr);
        m_jgAdapter.edit(cellAttr, null, null, null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setSize(new java.awt.Dimension(800, 600));

        jScrollPane1.setHorizontalScrollBarPolicy(javax.swing.ScrollPaneConstants.HORIZONTAL_SCROLLBAR_NEVER);
        jScrollPane1.setHorizontalScrollBar(null);
        jScrollPane1.setMinimumSize(new java.awt.Dimension(1280, 720));
        jScrollPane1.setPreferredSize(new java.awt.Dimension(1280, 720));
        getContentPane().add(jScrollPane1, java.awt.BorderLayout.CENTER);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private ListenableUndirectedGraph graph;
    private JGraphModelAdapter m_jgAdapter;
    private final double CANVAS_WIDTH = 1280;
    private final double LEVEL_MARGIN_DEPTH = 80;
    private final double TREE_MARGIN_DEPTH = 150;
    private double reached_depth = 20; // initially 20px height margin
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables
}
